produce RDF for begrepsrelasjon
Informasjonsforvaltning/concept-catalog pull request #101
Opened 2022-03-31 11:00 UTC by oyvindis

2022-03-31 11:50 UTC, stigbd requested changes

2022-03-31 11:50 UTC, stigbd commented on src/test/resources/collection_0.ttl
> +        skosno:begrepsrelasjon  [ rdf:type                    skosno:GeneriskRelasjon ;
`skosno:begrepsrelasjon` -> `skosno:generiskRelasjon`
ref https://data.norge.no/specification/skos-ap-no-begrep/#Begrep_generiskRelasjon

2022-03-31 11:50 UTC, stigbd commented on src/test/resources/collection_0.ttl
> +        skosno:begrepsrelasjon  [ rdf:type                skosno:AssosiativRelasjon ;
`skosno:begrepsrelasjon` -> `skosno:assosiativeRelasjon`
ref https://data.norge.no/specification/skos-ap-no-begrep/#Begrep_generiskRelasjon

2022-03-31 11:50 UTC, stigbd commented on src/test/resources/collection_0.ttl
> +        skosno:begrepsrelasjon  [ rdf:type                    skosno:PartitivRelasjon ;
`skosno:begrepsrelasjon` -> `skosno:partitivRelasjon`
ref https://data.norge.no/specification/skos-ap-no-begrep/#Begrep_partitivRelasjon

2022-04-06 08:30 UTC, oyvindis commented
Bruker oppdatert concept-builder slik at concept-catalog produserer rdf ihht. spec.

2022-04-06 10:08 UTC, stigbd requested changes
Veldig bra. Kun dette: Saknar ein test som testar isPartOf. Fint om vi får den på plass.

2022-04-06 11:57 UTC, stigbd approved these changes

2022-04-07 10:46 UTC, NilsOveTen requested changes

2022-04-07 10:46 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/concept_catalog/service/SkosApNoModelService.kt
> +            ?.let {
Blir det ikke samme om du dropper mellomsteget med let og kjører forEach direkte?
```suggestion
            ?.forEach {
```

2022-04-07 10:46 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/concept_catalog/service/SkosApNoModelService.kt
> +                            ?.filterValues { it.toString().isNotBlank() }
Ikke bruk samme variabelnavn for scope-funksjoner inne i andre scope-funksjoner:
```suggestion
                            ?.filterValues { beskrivelse -> beskrivelse.toString().isNotBlank() }
```

2022-04-07 10:46 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/concept_catalog/service/SkosApNoModelService.kt
> +                                it.forEach { (key, value) -> associativeRelationBuilder.description(value.toString(), key) }
igjen, tror du kan kjøre forEach direkte og kan droppe mellomsteget med `let`

2022-04-07 10:46 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/concept_catalog/service/SkosApNoModelService.kt
> +                            ?.takeIf { it.isNotEmpty() }
```suggestion
                            ?.takeIf { beskrivelse -> beskrivelse.isNotEmpty() }
```

2022-04-07 10:46 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/concept_catalog/service/SkosApNoModelService.kt
> +                            ?.filterValues { it.toString().isNotBlank() }
```suggestion
                            ?.filterValues { inndelingskriterium -> inndelingskriterium.toString().isNotBlank() }
```

2022-04-07 10:46 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/concept_catalog/service/SkosApNoModelService.kt
> +                            ?.takeIf { it.isNotEmpty() }
```suggestion
                            ?.takeIf { inndelingskriterium -> inndelingskriterium.isNotEmpty() }
```

2022-04-07 10:46 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/concept_catalog/service/SkosApNoModelService.kt
> +                            ?.let {
```suggestion
                            ?.forEach {
```

2022-04-07 10:46 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/concept_catalog/service/SkosApNoModelService.kt
> +                            ?.filterValues { it.toString().isNotBlank() }
```suggestion
                            ?.filterValues { inndelingskriterium -> inndelingskriterium.toString().isNotBlank() }
```

2022-04-07 10:46 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/concept_catalog/service/SkosApNoModelService.kt
> +                            ?.takeIf { it.isNotEmpty() }
```suggestion
                            ?.takeIf { inndelingskriterium.isNotEmpty() }
```

2022-04-07 10:46 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/concept_catalog/service/SkosApNoModelService.kt
> +                            ?.let {
```suggestion
                            ?.forEach {
```

2022-04-08 08:27 UTC, NilsOveTen approved these changes

2022-04-08 09:26 UTC, merged