fix: change relationRole to description in assosiativRelasjon skos v2
Informasjonsforvaltning/concept-catalog pull request #346
Opened 2024-05-16 08:37 UTC by hegeaal

closes #341 
closes #342

2024-05-16 08:44 UTC, terjesyl approved these changes

2024-05-16 11:22 UTC, NilsOveTen requested changes

2024-05-16 11:22 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/concept_catalog/rdf/SKOSNO.kt
> +        // val omfang: Property = ResourceFactory.createProperty( "${uri}omfang")
```suggestion
```

2024-05-16 11:22 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/concept_catalog/service/SkosApNoModelService.kt
> +            ?.let { source -> addURIText(SKOSNO.valueRange, source) }
ai, dette missa jeg nok i issuet. Det går over til å være direkte angivelse, men støtter både tekst og uri

du kan prioritere urier, dvs:
```
skosno:omfang [
  rdfs:label    "Test"@nb ;
  rdfs:seeAlso  <https://test.no>
]
```
blir til
```
skosno:valueRange <https://test.no>
```
og
```
skosno:omfang [
  rdfs:label    "Test"@nb
]
```
blir til
```
skosno:valueRange "Test"@nb
```

2024-05-16 13:11 UTC, hegeaal commented on src/main/kotlin/no/fdk/concept_catalog/service/SkosApNoModelService.kt
> +            ?.let { source -> addURIText(SKOSNO.valueRange, source) }
Hmm, jeg skjønner ikke helt, er det ikke det allerede? 

`data class URITekst (
    val uri: String? = null,
    val tekst: String? = null
)`

2024-05-21 08:00 UTC, NilsOveTen approved these changes

2024-05-21 08:21 UTC, merged