feat: adds term search
Informasjonsforvaltning/concept-catalog pull request #36
Opened 2021-06-04 14:29 UTC by matsjs

2021-06-07 13:00 UTC, NilsOveTen requested changes

2021-06-07 13:00 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/concept_catalog/controller/ConceptsController.kt
> +    fun searchBegrep(
Oppdater openapi plz

2021-06-07 13:03 UTC, NilsOveTen commented
dependabot klager på noe greier, kan du kjøre en rask oppdatering av dependecies i tillegg?

2021-06-08 12:01 UTC, NilsOveTen requested changes

2021-06-08 12:01 UTC, NilsOveTen commented on src/main/resources/specification/specification.yaml
> +    get:
Dette er vel ikke sant? Du la jo bare til en POST, eller har vi en /search fra før?

2021-06-08 12:01 UTC, NilsOveTen commented on src/main/resources/specification/specification.yaml
> +              $ref: '#/components/schemas/Begrep'
```suggestion
              $ref: '#/components/schemas/JsonSearchOperation'
```

2021-06-08 12:05 UTC, matsjs commented on src/main/resources/specification/specification.yaml
> +    get:
God catch, litt for mye som ble med der

2021-06-08 12:12 UTC, NilsOveTen approved these changes

2021-06-08 12:12 UTC, NilsOveTen commented on src/test/kotlin/no/fdk/concept_catalog/contract/SearchConcepts.kt
> +    fun `Empty query returns nothing`() {
```suggestion
    fun `Empty query responds with bad request`() {
```

2021-06-08 12:21 UTC, merged