feat: add security
Informasjonsforvaltning/concept-catalog pull request #5
Opened 2021-05-19 11:32 UTC by NilsOveTen

resolves #4

2021-05-19 11:51 UTC, azaxarov requested changes

2021-05-19 11:51 UTC, azaxarov commented on src/main/kotlin/no/fdk/concept_catalog/security/SecurityConfig.kt
> +            request.method == "GET"
```suggestion
        request?.getHeader(HttpHeaders.ACCEPT)?.contains(""text/turtle"") && request.method == HttpMethods.GET
```

2021-05-19 11:51 UTC, azaxarov commented on src/main/resources/application.yml
> +  fdkIssuer: ${SSO_HOST:https://sso.staging.fellesdatakatalog.digdir.no}/auth/realms/fdk
```suggestion
spring:
  security.oauth2.resourceserver.jwt.jwk-set-uri: ${SSO_HOST}/auth/realms/fdk/protocol/openid-connect/certs
  security.oauth2.resourceserver.jwt.issuer-uri: ${SSO_HOST:https://sso.staging.fellesdatakatalog.digdir.no}/auth/realms/fdk
```

2021-05-19 11:51 UTC, azaxarov commented on src/main/kotlin/no/fdk/concept_catalog/security/SecurityProperties.kt
> +data class SecurityProperties(
Denne data class er ikke nødvendig

2021-05-19 11:51 UTC, azaxarov commented on src/main/kotlin/no/fdk/concept_catalog/security/SecurityConfig.kt
> +                    JwtIssuerValidator(securityProperties.fdkIssuer),
```suggestion
                    JwtIssuerValidator(roperties.jwt.issuerUri),
```

2021-05-19 11:51 UTC, azaxarov commented on src/main/kotlin/no/fdk/concept_catalog/security/SecurityConfig.kt
> +) : WebSecurityConfigurerAdapter() {
```suggestion
open class SecurityConfig() : WebSecurityConfigurerAdapter() {
```

2021-05-20 05:23 UTC, NilsOveTen commented on src/main/resources/application.yml
> +  fdkIssuer: ${SSO_HOST:https://sso.staging.fellesdatakatalog.digdir.no}/auth/realms/fdk
ce0a85d

2021-05-20 05:24 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/concept_catalog/security/SecurityProperties.kt
> +data class SecurityProperties(
ce0a85d

2021-05-20 05:24 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/concept_catalog/security/SecurityConfig.kt
> +                    JwtIssuerValidator(securityProperties.fdkIssuer),
ce0a85d

2021-05-20 05:25 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/concept_catalog/security/SecurityConfig.kt
> +) : WebSecurityConfigurerAdapter() {
ce0a85d

2021-05-20 05:25 UTC, NilsOveTen commented on src/main/kotlin/no/fdk/concept_catalog/security/SecurityConfig.kt
> +            request.method == "GET"
c73575f

2021-05-20 07:06 UTC, azaxarov approved these changes

2021-05-20 07:29 UTC, merged