feat: add begrepsrelasjon to specification
Informasjonsforvaltning/concept-catalog pull request #91
Opened 2021-12-16 13:13 UTC by oyvindis

https://data.norge.no/specification/forvaltningsstandard-begrepsbeskrivelser/images/UML-v2.0.png:

![image](https://user-images.githubusercontent.com/6214701/146378411-d4bdefba-51e6-4637-9c75-b201a4be46d1.png)

2021-12-17 07:42 UTC, NilsOveTen approved these changes
Vi har i hovedsak prøvd å følge SKOS-AP-NO-Begrep mtp feltnavn, blir vel kalt `overordnetBegrep` og `underordnetBegrep` der.

2021-12-17 07:57 UTC, stigbd requested changes

2021-12-17 07:57 UTC, stigbd commented on src/main/resources/specification/specification.yaml
> +                'specializes':
Denne property burde heite `overordnetBegrep`.

2021-12-17 07:57 UTC, stigbd commented on src/main/resources/specification/specification.yaml
> +                'generalizes':
Denne property burde heite `underordnetBegrep`

2021-12-17 07:57 UTC, stigbd commented on src/main/resources/specification/specification.yaml
> +                'hasPart':
`underordnetBegrep`

2021-12-17 07:57 UTC, stigbd commented on src/main/resources/specification/specification.yaml
> +                'isPartOf':
`overordnetBegrep`

2021-12-17 07:57 UTC, stigbd commented on src/main/resources/specification/specification.yaml
> +          type: string
Alle disse som antagelegvis har id til det relaterte begrepet som verdi, burde ha ein description som seier dette, feks:
```
description: id of the related concept
```

2021-12-18 14:38 UTC, stigbd approved these changes

2021-12-20 08:39 UTC, matsjs approved these changes

2022-03-29 06:09 UTC, oyvindis commented
Closed as commit also was part of https://github.com/Informasjonsforvaltning/concept-catalog/pull/92

2022-03-29 06:09 UTC, closed without merging